







spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: microservice-master
        uri: lb://microservice-master
        predicates:
        - Path=/master/**
        filters:
        - StripPrefix=1
      - id: microservice-slave
        uri: lb://MICROSERVICE-SLAVE
        predicates:
        - Path=/slave/**
        filters:
        - StripPrefix=1
